-- Development Seed Data
-- This file is automatically loaded by Supabase on database reset

-- NOTE: No default organization inserted (Story 1.6 requirement)
-- Setup wizard creates the first organization on initial deployment
-- This ensures the setup wizard is triggered correctly on fresh deployments

-- Test Users for Development
-- NOTE: Supabase Auth manages the auth.users table, so test users must be created
-- via the signup UI or using the Supabase Auth API. User profiles are automatically
-- created via the /api/auth/create-profile endpoint after successful signup.
--
-- To create test users for development:
-- 1. Navigate to http://localhost:3000/signup
-- 2. Create accounts with the following emails:
--    - owner@test.com (first user - automatically gets 'owner' role)
--    - admin@test.com (manually promote to 'admin' role after creation)
--    - agent@test.com (manually promote to 'agent' role after creation)
--    - user@test.com (default 'end_user' role)
--
-- OR use Supabase Auth API:
-- See: https://supabase.com/docs/reference/javascript/auth-signup
--
-- Example role promotion (run after user signup):
-- UPDATE users SET role = 'admin' WHERE email = 'admin@test.com';
-- UPDATE users SET role = 'agent' WHERE email = 'agent@test.com';
