-- This file is intentionally a no-op.
--
-- Migrations are now applied by docker/scripts/run-migrations.sh, called from
-- docker/start.sh after the container is up.  The runner replays every file in
-- supabase/migrations/ in filename order and tracks progress in the
-- public._migrations table so re-deploys are safe.
--
-- Do NOT add DDL here — edit the appropriate file under supabase/migrations/ instead.
