/**
 * ProblemStatementCard Component
 * Story 3.3: Auto-Categorization of Pings with Conversational Clarification
 *
 * Displays AI-generated problem statement pinned at top of ping detail view.
 */

'use client';

import { useState, useEffect } from 'react';
import { ChevronDown, ChevronUp, Sparkles } from 'lucide-react';
import { cn } from '@/lib/utils';
import { CategoryBadge } from './category-badge';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { Button } from '@/components/ui/button';

interface Category {
  id: string;
  name: string;
  description?: string | null;
  color: string;
  icon?: string | null;
}

interface ProblemStatementCardProps {
  summary: string;
  category: Category | null;
  confidence?: number;
  collapsible?: boolean;
  className?: string;
}

export function ProblemStatementCard({
  summary,
  category,
  confidence,
  collapsible = true,
  className,
}: ProblemStatementCardProps) {
  const [isExpanded, setIsExpanded] = useState(true);

  // Load collapse state from localStorage
  useEffect(() => {
    if (collapsible) {
      const stored = localStorage.getItem('problemStatementCardExpanded');
      if (stored !== null) {
        setIsExpanded(stored === 'true');
      }
    }
  }, [collapsible]);

  // Save collapse state to localStorage
  const toggleExpanded = () => {
    const newState = !isExpanded;
    setIsExpanded(newState);
    if (collapsible) {
      localStorage.setItem('problemStatementCardExpanded', String(newState));
    }
  };

  if (!summary) {
    return null;
  }

  return (
    <Card className={cn('border-blue-200 bg-blue-50/50', className)}>
      <CardHeader className="pb-3">
        <div className="flex items-start justify-between">
          <div className="flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-blue-600" />
            <CardTitle className="text-base">Problem Summary</CardTitle>
          </div>
          {collapsible && (
            <Button
              variant="ghost"
              size="sm"
              onClick={toggleExpanded}
              className="h-8 w-8 p-0"
            >
              {isExpanded ? (
                <ChevronUp className="h-4 w-4" />
              ) : (
                <ChevronDown className="h-4 w-4" />
              )}
              <span className="sr-only">
                {isExpanded ? 'Collapse' : 'Expand'}
              </span>
            </Button>
          )}
        </div>
        <CardDescription className="flex items-center gap-2 text-xs">
          Generated by Echo
          {category && (
            <>
              <span className="text-gray-400">•</span>
              <CategoryBadge
                category={category}
                size="sm"
                showIcon={true}
                showConfidence={confidence !== undefined}
                confidence={confidence}
              />
            </>
          )}
        </CardDescription>
      </CardHeader>
      {isExpanded && (
        <CardContent>
          <p className="text-sm leading-relaxed text-gray-700">{summary}</p>
        </CardContent>
      )}
    </Card>
  );
}

/**
 * Loading skeleton for ProblemStatementCard
 */
export function ProblemStatementCardSkeleton() {
  return (
    <Card className="border-blue-200 bg-blue-50/50">
      <CardHeader className="pb-3">
        <div className="flex items-center gap-2">
          <Sparkles className="h-5 w-5 animate-pulse text-blue-600" />
          <CardTitle className="text-base">
            Generating problem summary...
          </CardTitle>
        </div>
        <CardDescription className="text-xs">
          Echo is analyzing the conversation
        </CardDescription>
      </CardHeader>
      <CardContent>
        <div className="space-y-2">
          <div className="h-4 w-full animate-pulse rounded bg-gray-200" />
          <div className="h-4 w-5/6 animate-pulse rounded bg-gray-200" />
          <div className="h-4 w-4/6 animate-pulse rounded bg-gray-200" />
        </div>
      </CardContent>
    </Card>
  );
}
