-- Allow NULL title for draft pings (Story 3.2: AI-driven ping creation)
-- Title will be generated by AI after Echo conversation completes
ALTER TABLE pings ALTER COLUMN title DROP NOT NULL;

-- Add comment explaining why title can be null
COMMENT ON COLUMN pings.title IS 'Ping title. Can be NULL for draft pings during Echo conversation. Must be set before ping status changes from draft.';
